[package]
name = "dive_6_serde_crate"
version = "0.1.0"
edition = "2024"

[dependencies]
hello_macro = { path = "./hello_macro" }
hello_macro_derive = { path = "./hello_macro_derive" }
quote = "1.0.40"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
syn = "2.0.106"
